apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: pra
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: alpine
      command: ["sh", "-c", "ls -la /data"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pra-data
